# Generated by Django 3.2.6 on 2021-08-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='available',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('stars', models.DecimalField(decimal_places=1, max_digits=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
    ]
